### ISSUE TITLE
Setup Redux

### ISSUE THREAD

**Issue by longhoang0304** [swomfire/react-link#1]
Setup redux bao gồm

- Folder reducers
- Folder stores
- Dùng react-redux

**Comment by R-Jim** [comment]
Folder stores là sao anh

**Comment by longhoang0304** [comment]
Là mình sẽ bỏ một hàm để create store.
Chứ mình không tạo store trực tiếp trong file `App.js` hoặc `index.js`

Vì store sau này có middleware, config nhiều, nên mình nên bỏ vào một file để dễ quản lý hơn.
